### ISSUE TITLE
Opening a part from a design should focus the highlighted part in the sequence map in VE

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#251]
### Describe what's going wrong/what needs to change.
When double-clicking a part in a design it opens it in Vector Editor but in the Sequence Map you have to scroll to find that part, it is highlighted but it's not focused on the screen by default.
### Steps to reproduce the behavior
Double-click a part in any design to open it in VE.
### Screenshots/gif of issue
![focus part](https://user-images.githubusercontent.com/21211903/36929603-f1ceb120-1e47-11e8-8273-2d0bf881dee9.gif)

**Comment by tnrich** [comment]
This should be fixed whenever hde updates to open-vector-editor@1.1.30 @craftjk @mmatena

**Comment by njhillson** [comment]
@XimeMora this is not JBEI feature - please test.

**Comment by XimeMora** [comment]
@tnrich this seems to work with some parts but if I use the same part from the gif above it is still not focusing that highlighted part on the screen, I still have to scroll to find it.

**Comment by AdamZMc** [comment]
Looks good to me!

**Comment by tnrich** [comment]
@XimeMora can you try this one out again? I think it should be better now.

**Comment by AdamZMc** [comment]
Looks good!

**Comment by XimeMora** [comment]
@tnrich this issue is still happening for me.

**Comment by tnrich** [comment]
This should be fixed once https://github.com/TeselaGen/hde/commit/32e6123fc4215841b95faa57e8f9fe16d9dfec73 makes it to dev. @mmatena do you know when that will be?

**Comment by XimeMora** [comment]
So far this issue is still happening on hde.

**Comment by XimeMora** [comment]
I'll fail this one because I still have to scroll to search for the highlighted part.

**Comment by XimeMora** [comment]
@tnrich @tiffanydai now what I'm seeing is that double-clicking on a part in the design editor doesn't highlight that part in the vector editor at all, could you help with this?

![highlight](https://user-images.githubusercontent.com/21211903/46638685-5d754480-cb62-11e8-9df1-b6bbc9b27dea.gif)

**Comment by tnrich** [comment]
@tiffanydai might this be related to your recent changes in hde? I am not sure why this would have stopped working..

**Comment by tiffanydai** [comment]
@tnrich hmmm I'm leaving today's 'componentWillMount' fix for a future PR/QA, and the only other non-alignment-specific fix was the 'fetchPolicy: "network-only"', which shouldn't affect the highlighting. It doesn't seem to be working on checked-out branches from days/weeks ago either...I created a PR for a fix (https://github.com/TeselaGen/hde/pull/2284), maybe you or @craftjk can take a look? 

Seems like we're setting the selection layer here: 
![screen shot 2018-10-09 at 12 10 20 am](https://user-images.githubusercontent.com/35508772/46652408-d3c07980-cb57-11e8-91d1-d8154a6fcb37.png)

But then the fix for https://github.com/TeselaGen/openVectorEditor/issues/336 seems to be resetting the selection layer upon loading the sequence: 
![screen shot 2018-10-09 at 12 13 36 am](https://user-images.githubusercontent.com/35508772/46652548-36b21080-cb58-11e8-9948-41bfaa8bcb4b.png)

So I think to still resolve issue 336 but not undo the selection layer when highlighting part, we can just reset the selection layer on unmount? 
![screen shot 2018-10-08 at 11 58 52 pm](https://user-images.githubusercontent.com/35508772/46652584-53e6df00-cb58-11e8-838c-0edebe1f4d51.png)

**Comment by XimeMora** [comment]
Parts are highlighted now, however sometimes I still have to scroll to find the highlighted part in the sequence map 😞  @tiffanydai @tnrich

**Comment by tiffanydai** [comment]
Not loading at the highlighted part's position seemed to only happen if the user clicked and left the caret somewhere else when looking at a previous sequence. I'm clearing the caret position upon loading now; let me know if it's still happening

**Comment by XimeMora** [comment]
This is working nicely now! Thanks! 👏
