### ISSUE TITLE
Copy Options not working

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#305]
The right click menus 'Copy > Copy' and 'Copy > Copy Options' are broken, they don't do anything.

![copyoptions](https://user-images.githubusercontent.com/21211903/39288613-89f5ed1e-48dd-11e8-8f28-135d050fc8f8.gif)

**Comment by XimeMora** [comment]
Copy options seem to work but I can't fully test it because the copied base pairs can't be pasted, it seems that the selection has some extra quote marks and that's why I'm getting the "Sorry no valid base pairs to paste"

![novalidbps](https://user-images.githubusercontent.com/21211903/39597868-9f63e9dc-4ecb-11e8-85cf-646e570871ce.gif)

**Comment by tnrich** [comment]
@XimeMora  this should be fixed now.

**Comment by AdamZMc** [comment]
Looks great!

**Comment by XimeMora** [comment]
@tnrich I'm still getting the "Sorry no valid base pairs to paste" message.

**Comment by tnrich** [comment]
@XimeMora can you check this one again? I believe a fix has been implemented

**Comment by XimeMora** [comment]
I was able to paste base pairs correctly 👍 
I'll pass this ticket and create a new one for anothe issue with the copy options not working properly.
