### ISSUE TITLE
Broken package.json since 18.2.35

### ISSUE THREAD

**Issue by smeng9** [TeselaGen/openVectorEditor#897]
@tnrich

I have noticed this commit breaks the package published on npmjs https://github.com/TeselaGen/openVectorEditor/commit/70ce1c9041991b39b6207d08757310c1160adb46#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R5

The published package on npmjs https://www.npmjs.com/package/open-vector-editor/v/18.2.35?activeTab=code does not include dist folder so bundler cannot correctly resolve files

**Comment by smeng9** [comment]
Hi @tnrich,

Are we planning to revert this change? Any new published package is not usable.

What is your current setup to run OVE > 18.2.35?

**Comment by tnrich** [comment]
Hi Smeng sorry for the breakage. I'll look into this tomorrow and fix it.

**Comment by tnrich** [comment]
Hi @smeng9 I think this was already fixed, see the latest version - https://www.npmjs.com/package/open-vector-editor/v/18.3.1

**Comment by smeng9** [comment]
Hi @tnrich the issues persists in 18.3.1 on npmjs.

In line 8 of the package.json https://www.npmjs.com/package/open-vector-editor/v/18.3.1?activeTab=code it tries to import ./dist/index.mjs

In the published package itself https://www.npmjs.com/package/open-vector-editor/v/18.3.1?activeTab=code it has lib/ folder instead of dist/ folder.

I suggest we revert the change of line 5 and line 8 in aforementioned commit https://github.com/TeselaGen/openVectorEditor/commit/70ce1c9041991b39b6207d08757310c1160adb46#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R5

**Comment by tnrich** [comment]
@smeng9 thanks for the explanation, didn't realize I had forgotten those lines. They're back as they were now. Lemme know if that fixes things for you.

**Comment by smeng9** [comment]
Problem is solved, Thanks!
